.PHONY: ts1 ts2 ts3 py1 py2 py3

ts1:
	npx tsx typescript/drill_01_file_storage.ts

ts2:
	npx tsx typescript/drill_02_key_value_store.ts

ts3:
	npx tsx typescript/drill_03_feature_flag_service.ts

py1:
	python3 python/drill_01_file_storage.py

py2:
	python3 python/drill_02_key_value_store.py

py3:
	python3 python/drill_03_feature_flag_service.py
